server:
  port: 8002
    
spring:
  application: 
    name: sc-provider
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/news2?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: sc-provider-8002   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: sc-provider-8002
  company.name: www.jd.com
  build.artifactId: service-cloud-provider-8002
  build.version: 0.0.1-SNAPSHOT